mod day1;
mod day2;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;
mod day10;
mod day11;
mod day12;

use crate::day1::{day1part1, day1part2};
use crate::day2::{day2part1, day2part2};
use crate::day3::{day3part1, day3part2};
use crate::day4::{day4part1, day4part2};
use crate::day5::{day5part1, day5part2};
use crate::day6::{day6part1, day6part2};
use crate::day7::{day7part1, day7part2};
use crate::day8::{day8part1, day8part2};
use crate::day9::{day9part1, day9part2};
use crate::day10::{day10part1, day10part2};
use crate::day11::{day11part1, day11part2};
use crate::day12::{day12part1, day12part2};
use std::fs::read_to_string;

fn main() {
    println!("Hello, world!");
    let s = read_to_string("input/day1.txt").expect("Unable to open file.");
    println!("Day 1 Part 1: {}", day1part1(&s));
    println!("Day 1 Part 2: {}", day1part2(&s));
    let s = read_to_string("input/day2.txt").expect("Unable to open file.");
    println!("Day 2 Part 1: {}", day2part1(&s));
    println!("Day 2 Part 2: {}", day2part2(&s));
    let s = read_to_string("input/day3.txt").expect("Unable to open file.");
    println!("Day 3 Part 1: {}", day3part1(&s));
    println!("Day 3 Part 2: {}", day3part2(&s));
    let s = read_to_string("input/day4.txt").expect("Unable to open file.");
    println!("Day 4 Part 1: {}", day4part1(&s));
    println!("Day 4 Part 2: {}", day4part2(&s));
    let s = read_to_string("input/day5.txt").expect("Unable to open file.");
    println!("Day 5 Part 1: {}", day5part1(&s));
    println!("Day 5 Part 2: {}", day5part2(&s));
    let s = read_to_string("input/day6.txt").expect("Unable to open file.");
    println!("Day 6 Part 1: {}", day6part1(&s));
    println!("Day 6 Part 2: {}", day6part2(&s));
    let s = read_to_string("input/day7.txt").expect("Unable to open file.");
    println!("Day 7 Part 1: {}", day7part1(&s));
    println!("Day 7 Part 2: {}", day7part2(&s));
    let s = read_to_string("input/day8.txt").expect("Unable to open file.");
    println!("Day 8 Part 1: {}", day8part1(&s));
    println!("Day 8 Part 2: {}", day8part2(&s));
    let s = read_to_string("input/day9.txt").expect("Unable to open file.");
    println!("Day 9 Part 1: {}", day9part1(&s));
    println!("Day 9 Part 2: {}", day9part2(&s));
    let s = read_to_string("input/day10.txt").expect("Unable to open file.");
    println!("Day 9 Part 1: {}", day10part1(&s));
    println!("Day 9 Part 2: {}", day10part2(&s));
    let s = read_to_string("input/day11.txt").expect("Unable to open file.");
    println!("Day 9 Part 1: {}", day11part1(&s));
    println!("Day 9 Part 2: {}", day11part2(&s));
    let s = read_to_string("input/day12.txt").expect("Unable to open file.");
    println!("Day 9 Part 1: {}", day12part1(&s));
    println!("Day 9 Part 2: {}", day12part2(&s));
}
